In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("diabetes.csv")

In [5]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Pedigree,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
data.isnull().sum()

Pregnancies      0
Glucose          0
BloodPressure    0
SkinThickness    0
Insulin          0
BMI              0
Pedigree         0
Age              0
Outcome          0
dtype: int64

In [9]:
for column in data.columns[1:-3]:
    data[column].replace(0, np.NAN, inplace = True)
    data[column].fillna(round(data[column].mean(skipna = True)), inplace = True)

In [11]:
data.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Pedigree,Age,Outcome
0,6,148.0,72.0,35.0,156.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,156.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,156.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
5,5,116.0,74.0,29.0,156.0,25.6,0.201,30,0
6,3,78.0,50.0,32.0,88.0,31.0,0.248,26,1
7,10,115.0,72.0,29.0,156.0,35.3,0.134,29,0
8,2,197.0,70.0,45.0,543.0,30.5,0.158,53,1
9,8,125.0,96.0,29.0,156.0,32.0,0.232,54,1

In [13]:
X = data.iloc[:, :8]
Y = data.iloc[:, 8:]

In [15]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [21]:
knn = KNeighborsClassifier()
knn_fit = knn.fit(X_train, y_train.values.ravel())
knn_pred = knn_fit.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score

In [27]:
print("Confusion Matrix: ")
print(confusion_matrix(y_test, knn_pred))
print("Accuracy score: ", accuracy_score(y_test, knn_pred))
print("Recall score: ", recall_score(y_test, knn_pred))
print("F1 score: ", f1_score(y_test, knn_pred))
print("Precision Score: ", precision_score(y_test, knn_pred))

Confusion Matrix:
[[66 33]
 [20 35]]
Accuracy score:  0.6558441558441559
Recall score:  0.6363636363636364
F1 score:  0.5691056910569106
Precision Score:  0.5147058823529411